### ISSUE TITLE
Instructions for packaging for M1 mac

### ISSUE THREAD

**Issue by DoctorMikeReddy** [cppchriscpp/create-nes-game#5]
pkg can target node16-macos-arm64 but I cannot work out how to create an executable without the following error on run:

mreddy01@Little-Vic create-nes-game-1.0.12 % ./create-nes-game
[create-nes-game] [error] Unable to run command update Error: Cannot find module './commands/update'
Require stack:
- /snapshot/create-nes-game-1.0.12/index.js
1) If you want to compile the package/file into executable, please pay attention to compilation warnings and specify a literal in 'require' call. 2) If you don't want to compile the package/file into executable and want to 'require' it from filesystem (likely plugin), specify an absolute path in 'require' call using process.cwd() or process.execPath.
    at Function.Module._resolveFilename (node:internal/modules/cjs/loader:933:15)
    at Function._resolveFilename (pkg/prelude/bootstrap.js:1951:46)
    at Function.Module._load (node:internal/modules/cjs/loader:778:27)
    at Module.require (node:internal/modules/cjs/loader:1005:19)
    at Module.require (pkg/prelude/bootstrap.js:1851:31)
    at require (node:internal/modules/cjs/helpers:102:18)
    at /snapshot/create-nes-game-1.0.12/index.js
    at process.runNextTicks [as _tickCallback] (node:internal/process/task_queues:61:5)
    at Function.runMain (pkg/prelude/bootstrap.js:1980:13)
    at node:internal/main/run_main_module:17:47 {
  code: 'MODULE_NOT_FOUND',
  requireStack: [ '/snapshot/create-nes-game-1.0.12/index.js' ],
  pkg: true
}

**Comment by DoctorMikeReddy** [comment]
[package.json](https://github.com/cppchriscpp/create-nes-game/files/13175236/package.json)
 I think that this needs to be edited to include M1 Mac, but also some command line option for the pkg command. Can you help?

**Comment by cppchriscpp** [comment]
Sorry, but I will not be supporting macs with this tool due to the complexity of supporting the mac ecosystem. Please use the tool under either Windows or Linux.
